behavior_fsm_node:
  ros__parameters:
    use_sim_time: true
    lane_model_topic: /qcar2/lane/model
    obstacle_state_topic: /qcar2/obstacle/state
    behavior_state_topic: /qcar2/behavior/state
    min_lane_confidence: 0.3
    publish_rate: 10.0
    desired_speed: 0.25
    normal_speed: 0.25
    lane_change_speed: 0.18
    slow_speed: 0.12
    prepare_duration_sec: 0.4
    lane_change_duration_sec: 3.0
    min_pass_time_sec: 1.2
    clear_hold_sec: 0.8
    obstacle_timeout_sec: 0.8
